skip-check:
  - CKV_AZURE_172 # Enable auto-rotation of Secrets Store CSI Driver secrets
  - CKV_AZURE_226 # Use ephemeral disks
  - CKV_AZURE_227 # Ensure encryption of temp disks, caches, and data flows
  - CKV_AZURE_232 # Ensure only critical system pods run on system nodes
  - CKV_AZURE_29  # Enable Azure CNI networking
  - CKV_AZURE_6   # Enable API server authorized IP ranges
  - CKV_AZURE_116 # Enable Azure Policies Add-on
  - CKV_AZURE_4   # Enable Azure Monitor logging
  - CKV_AZURE_170 # Use Paid SKU for SLA
  - CKV_AZURE_141 # Disable local admin account
  - CKV_AZURE_117 # Use disk encryption set
  - CKV_AZURE_171 # Ensure AKS cluster upgrade channel is chosen
  - CKV_AZURE_115 # Ensure private clusters
  - CKV_AZURE_7   # Ensure network policy is configured