skip-check:
  - CKV2_AZURE_21 # Ensure Storage logging is enabled for Blob service for read requests
  - CKV_AZURE_33 # Ensure Storage logging is enabled for Queue service
  - CKV_AZURE_206 # Ensure that Storage Accounts use replication
  - CKV_AZURE_59  # Ensure that Storage accounts disallow public access
  - CKV_AZURE_44  # Ensure Storage Account is using the latest version of TLS encryption
  - CKV_AZURE_190 # Ensure that Storage blobs restrict public access
  - CKV2_AZURE_47 # Ensure storage account is configured without blob anonymous access
  - CKV2_AZURE_40 # Ensure storage account is not configured with Shared Key authorization
  - CKV2_AZURE_38 # Ensure soft-delete is enabled on Azure storage account
  - CKV2_AZURE_41 # Ensure storage account is configured with SAS expiration policy
  - CKV2_AZURE_33 # Ensure storage account is configured with private endpoint
  - CKV2_AZURE_1  # Ensure storage for critical data are encrypted with Customer Managed Key
