// Query to find pods starting with 'idms-mailer', created after March 1, 2025, and aged more than 50 days
   let endDateTime = now();
   let startDateTime = datetime(2025-03-01T00:00:00Z);
   KubePodInventory
   | where TimeGenerated < endDateTime
   | where TimeGenerated >= startDateTime
   | where Name hasprefix 'idms-mailer'
   | extend PodAgeDays = datetime_diff('day', endDateTime, PodCreationTimeStamp)
   | where PodAgeDays > 50
   | distinct ClusterId, PodUid, PodCreationTimeStamp, Name, PodAgeDays, PodStatus